{
 "title": "US Census",
 "time": { "from": "2011-01-01T00:00:00.000Z", "to": "2021-01-01T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "Sex", "query": "1" },
   { "name": "Age", "query": "25" },
   { "name": "Education", "query": "22" },
   { "name": "Marital_status", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Predicted salary for input variables",
   "type": "stat",
   "description": "Change variables above",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  prediction as Prediction\nFROM predictions\nWHERE sex=$Sex AND agep=$Age AND schl=$Education AND mar=$Marital_status"
    }
   ]
  },
  {
   "title": "Average age",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  STR_TO_DATE(CONCAT(yoep, '-01-01'), '%Y-%m-%d') AS 'Year',\r\n  AVG(agep) as 'Average age'\r\nFROM data\r\nGROUP BY year;"
    }
   ]
  },
  {
   "title": "Average age per gender",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cast(yoep as char) as Year,\r\n  AVG(CASE WHEN sex = '1' THEN agep END) AS 'Men',\r\n  AVG(CASE WHEN sex = '2' THEN agep END) AS 'Women'\r\nFROM data\r\nWHERE agep>0\r\nGROUP BY year;"
    }
   ]
  },
  {
   "title": "Proportion of men and women that are on active duty in military per year",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  cast(yoep as char) as Year,\r\n  AVG(CASE WHEN sex = '1' AND mil = 1 THEN 1 ELSE 0 END) AS \"Men\",\r\n  AVG(CASE WHEN sex = '2' AND mil = 1 THEN 1 ELSE 0 END) AS \"Women\"\r\nFROM data\r\nGROUP BY Year;"
    }
   ]
  },
  {
   "title": "Average travel time to work per year",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  SUM(CASE WHEN yoep = '2011' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2011' AND jwmnp != 0 THEN jwmnp END) AS '2011',\r\n  SUM(CASE WHEN yoep = '2012' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2012' AND jwmnp != 0 THEN jwmnp END) AS '2012',\r\n  SUM(CASE WHEN yoep = '2013' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2013' AND jwmnp != 0 THEN jwmnp END) AS '2013',\r\n  SUM(CASE WHEN yoep = '2014' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2014' AND jwmnp != 0 THEN jwmnp END) AS '2014',\r\n  SUM(CASE WHEN yoep = '2015' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2015' AND jwmnp != 0 THEN jwmnp END) AS '2015',\r\n  SUM(CASE WHEN yoep = '2016' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2016' AND jwmnp != 0 THEN jwmnp END) AS '2016',\r\n  SUM(CASE WHEN yoep = '2017' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2017' AND jwmnp != 0 THEN jwmnp END) AS '2017',\r\n  SUM(CASE WHEN yoep = '2018' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2018' AND jwmnp != 0 THEN jwmnp END) AS '2018',\r\n  SUM(CASE WHEN yoep = '2019' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2019' AND jwmnp != 0 THEN jwmnp END) AS '2019',\r\n  SUM(CASE WHEN yoep = '2020' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2020' AND jwmnp != 0 THEN jwmnp END) AS '2020',\r\n  SUM(CASE WHEN yoep = '2021' AND jwmnp != 0 THEN jwmnp ELSE 0 END) / COUNT(CASE WHEN yoep = '2021' AND jwmnp != 0 THEN jwmnp END) AS '2021'\r\nFROM data\r\n"
    }
   ]
  },
  {
   "title": "Average gross rent per year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  STR_TO_DATE(CONCAT(yoep, '-01-01'), '%Y-%m-%d') AS 'year',\r\n  AVG(grntp) AS 'Average gross rent'\r\nFROM data\r\nWHERE grntp > 0\r\nGROUP BY year\r\n"
    }
   ]
  },
  {
   "title": "Average gross rent as a percentage of household income",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  STR_TO_DATE(CONCAT(yoep, '-01-01'), '%Y-%m-%d') AS 'year',\r\n  AVG(grpip) AS 'Average gross percentage'\r\nFROM data\r\nWHERE grntp > 0\r\nGROUP BY year\r\n"
    }
   ]
  },
  {
   "title": "Average percentage of married people",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  STR_TO_DATE(CONCAT(yoep, '-01-01'), '%Y-%m-%d') AS 'Year',\r\n  SUM(mar = 1) / COUNT(*) as Proportion\r\nFROM data\r\nGROUP BY year;"
    }
   ]
  },
  {
   "title": "Average gross rent as a percentage of household income per educational level",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT edu as Education, AVG(grpip) AS 'Average rent as percentage of income'\r\nFROM (\r\n  SELECT schl,\r\n    CASE\r\n      WHEN schl < 16 THEN '0'\r\n      WHEN schl BETWEEN 16 AND 19 THEN 'High school'\r\n      WHEN schl BETWEEN 20 AND 21 THEN 'Bachelor''s'\r\n      WHEN schl BETWEEN 22 AND 23 THEN 'Master''s'\r\n      WHEN schl = 24 THEN 'Doctorate'\r\n    END AS edu,\r\n    grpip\r\n  FROM data\r\n) AS edu_grpip\r\nWHERE edu != '0'\r\nGROUP BY edu\r\nORDER BY FIELD(edu, 'high school', 'bachelor''s', 'master''s', 'doctorate');"
    }
   ]
  },
  {
   "title": "Proportion of languages in non-english speaking households in 2011",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT hhlanp_mapped, \r\n       CAST(count_per_code AS FLOAT)/6766 AS proportion\r\nFROM (\r\n  SELECT hhlanp_mapped, \r\n         SUM(count_per_code) AS count_per_code\r\n  FROM (\r\n    SELECT yoep,\r\n           CASE\r\n             WHEN hhlanp = '1200' THEN 'Spanish'\r\n             WHEN hhlanp = '1970' THEN 'Chinese'\r\n             WHEN hhlanp = '2920' THEN 'Tagalog'\r\n             WHEN hhlanp = '4500' THEN 'Arabic'\r\n             ELSE 'Other'\r\n           END AS hhlanp_mapped,\r\n           COUNT(*) AS count_per_code,\r\n           DENSE_RANK() OVER (PARTITION BY yoep ORDER BY COUNT(*) DESC) AS row_num\r\n    FROM data\r\n    WHERE hhlanp NOT IN ('9500', 'N') and yoep=2011\r\n    GROUP BY yoep, hhlanp_mapped\r\n  ) AS subquery\r\n  WHERE row_num <= 5 OR hhlanp_mapped = 'Other'\r\n  GROUP BY yoep, hhlanp_mapped\r\n) AS subquery2\r\nGROUP BY hhlanp_mapped, count_per_code"
    }
   ]
  },
  {
   "title": "Proportion of languages in non-english speaking households in 2021",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT hhlanp_mapped, \r\n       CAST(count_per_code AS FLOAT)/5108 AS proportion\r\nFROM (\r\n  SELECT hhlanp_mapped, \r\n         SUM(count_per_code) AS count_per_code\r\n  FROM (\r\n    SELECT yoep,\r\n           CASE\r\n             WHEN hhlanp = '1200' THEN 'Spanish'\r\n             WHEN hhlanp = '1970' THEN 'Chinese'\r\n             WHEN hhlanp = '4500' THEN 'Arabic'\r\n             WHEN hhlanp = '1350' THEN 'Hindi'\r\n             ELSE 'Other'\r\n           END AS hhlanp_mapped,\r\n           COUNT(*) AS count_per_code,\r\n           DENSE_RANK() OVER (PARTITION BY yoep ORDER BY COUNT(*) DESC) AS row_num\r\n    FROM data\r\n    WHERE hhlanp NOT IN ('9500', 'N') and yoep=2021\r\n    GROUP BY yoep, hhlanp_mapped\r\n  ) AS subquery\r\n  WHERE row_num <= 5 OR hhlanp_mapped = 'Other'\r\n  GROUP BY yoep, hhlanp_mapped\r\n) AS subquery2\r\nGROUP BY hhlanp_mapped, count_per_code"
    }
   ]
  }
 ]
}